platform :ios, deployment_target: '8.0'

#pod 'DTFormMenuController', :git => 'https://github.com/DTHENG/DTFormMenuController.git'
pod 'DTFormMenuController', :path => '/Users/danielthengvall/DTFormMenuController/'
